#################################
#             General           #
#################################
backend			= "glx";
glx-no-stencil	= true;
vsync			= true;
transparent-clipping = true;

wintypes:
{
	tooltip = {
		fade = false;
		shadow = false;
		opacity = 1.0;
		focus = true;
	};
	dock = {
		shadow = false;
	};
};

#################################
#             Opacity           #
#################################
active-opacity = 0.95;
inactive-opacity = 0.8;

frame-opacity = 0.9;

opacity-rule = [
	"100:class_g = 'i3bar'",
	"100:class_g = 're.sonny.Workbench'",
	"100:class_g = 'Chromium'",
	"100:class_g = 'firefox-esr'",
	"100:class_g = 'thunderbird-default'",
	"100:window_type = 'dock'",
    "100:window_type = 'notification'"
]

transparent-clipping-exclude = [
	"!class_g = 'Alacritty'"
];

#################################
#             Fading            #
#################################
fading = true;
fade-delta = 3;

#################################
#             Corners           #
#################################
corner-radius = 0;
round-borders = 0;

rounded-corners-exclude = [
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"fullscreen"
];

#################################
#             Shadows           #
#################################
shadow = true;
shadow-radius = 25;
shadow-offset-x = -25;
shadow-offset-y = -25;
shadow-opacity = 0.5;
shadow-ignore-shaped = true;

shadow-exclude = [
	"_NET_WM_WINDOW_TYPE@:32a *= '_NET_WM_WINDOW_TYPE_DOCK'",
    "_NET_WM_WINDOW_TYPE@:32a *= '_NET_WM_WINDOW_TYPE_DESKTOP'",
    "_NET_WM_WINDOW_TYPE@:32a *= '_NET_WM_WINDOW_TYPE_TOOLTIP'",
    "_NET_WM_WINDOW_TYPE@:32a *= '_NET_WM_WINDOW_TYPE_POPUP_MENU'",
    "_NET_WM_WINDOW_TYPE@:32a *= '_NET_WM_WINDOW_TYPE_DROPDOWN_MENU'",
    "_NET_WM_WINDOW_TYPE@:32a *= '_NET_WM_WINDOW_TYPE_MENU'",
];

#################################
#             Blur				#
#################################
blur-background = true;
blur-method     = "dual_kawase";
blur-strength	= 4
blur-kern		= "3x3box";

blur-background-frame = false;
blur-background-fixed = false;

blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "window_type = 'popup_menu'",
    "window_type = 'dropdown_menu'",
    "window_type = 'utility'",
    "window_type = 'tooltip'",
    "window_type = 'menu'",
    "class_g = 'i3bar'",
];
